name: tekartik_pub
version: 0.10.0
description: Pub and package helpers
homepage: https://github.com/tekartik/pub.dart
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  process_run: '>=0.6.0-dev.1'
  yaml: any
  fs_shim: '>=0.10.0'
  pub_semver: any
  args: any
  dart2_constant: '>=1.0.1'
dev_dependencies:
  tekartik_fs_test:
    git:
      url: git://github.com/tekartik/fs_shim.dart
      ref: dart2
      path: fs_test
  dev_test: any
  test: '>=1.2.0'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  async: '>=2.0.7'
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
test_dependencies:
- process_run
dependency_overrides:
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
executables:
  pubget: pubget
  pubupgrade: pubupgrade