name: tekartik_pub
version: 0.5.0
description: Pub and package helpers
homepage: https://github.com/tekartik/tekartik_pub.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  process_run: any
  yaml: any
  fs_shim: any
  pub_semver: any
  args: any
dev_dependencies:
  fs_shim_test:
    git: git://github.com/tekartik/fs_shim_test.dart
  dev_test: any
  test: any
test_dependencies:
- process_run
dependency_overrides:
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
executables:
  pubget: pubget
  pubupgrade: pubupgrade