name: tekartik_pub
version: 0.12.4
description: Pub and package helpers
homepage: https://github.com/tekartik/pub.dart
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  dev_test:
  path:
  process_run: '>=0.10.3'
  yaml: any
  fs_shim: '>=2.2.0'
  pub_semver: any
  args: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.8'

dev_dependencies:
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      ref: dart2_3
      path: fs_test
    version: '>=0.4.3'
  test: '>=1.2.0'
  build_runner: '>=1.2.7'
  build_test: '>=0.10.2'
  async: '>=2.0.7'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2_3
  chrome_travis:
    git:
      url: https://github.com/tekartik/chrome_travis.dart
      ref: dart2_3
test_dependencies:
- process_run

# dependency_overrides:
#  process_run:
#    path: ../../../github.com/tekartik/process_run.dart
#  dev_test:
#    path: ../dev_test.dart/dev_test
#  process_run:
#    git: https://github.com/tekartik/process_run.dart
#  fs_shim:
#    git: https://github.com/tekartik/fs_shim.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart