name: tekartik_pub
version: 0.1.0
description: Pub and package helpers
homepage: https://github.com/tekartik/tekartik_pub.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  cmdo:
    git: git://github.com/tekartik/cmdo.dart
dev_dependencies:
  dev_test: any
  test: any

